# Generated by Django 5.2.6 on 2025-10-01 08:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("high_level", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matierepremiere",
            name="stock",
        ),
    ]
